name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 17 7 * * 3
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  test:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # TODO upgrade to 1.8.2+ when https://github.com/jqlang/jq/pull/3570 is merged and released
          - name: jq 1.8.1
            url: https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-linux-amd64
            # https://github.com/jqlang/jq/releases/download/jq-1.8.1/sha256sum.txt
            sha256: 020468de7539ce70ef1bceaf7cde2e8c4f2ca6c3afb84642aabc5c97d9fc2a0d
          - name: jq 1.7.1
            url: https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64
            # https://github.com/jqlang/jq/releases/download/jq-1.7.1/sha256sum.txt
            sha256: 5942c9b0934e510ee61eb3e30273f1b3fe2590df93933a93d7c58b81d19c8ff5
          # TODO jaq (--run-tests does not support module loading; needs a different test runner)
          # - name: jaq 3.1.0
          #   url: https://github.com/01mf02/jaq/releases/download/v3.1.0/jaq-x86_64-unknown-linux-gnu
          #   # https://api.github.com/repos/01mf02/jaq/releases/tags/v3.1.0 (assets[].digest)
          #   sha256: 093d741fdd262467f33a4c326acf989e05b03e36677ba190220ca6798326be86
      fail-fast: false
    steps:
      - uses: tianon/actions/checkout/composite@581498642ee39d41dc3a801d22b3f7f42a95acc7 # HEAD

      - name: install ${{ matrix.name }}
        env:
          URL: ${{ matrix.url }}
          SHA256: ${{ matrix.sha256 }}
        run: |
          curl --fail --silent --show-error --location --output /usr/local/bin/jq-ish "$URL"
          sha256sum --check --strict <<< "$SHA256 */usr/local/bin/jq-ish"
          chmod +x /usr/local/bin/jq-ish
          jq-ish --version

      - name: '*.jqtest'
        run: |
          exitCode=0
          for f in *.jqtest; do
            jq-ish --run-tests "$f" || (( ++exitCode ))
          done
          exit "$exitCode"
